apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qjhwot4hl-nodejs
  janus-idp.io/tekton: qjhwot4hl-nodejs
  backstage.io/kubernetes-id: qjhwot4hl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qjhwot4hl-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
