apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qjhwot4hl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qjhwot4hl-nodejs 
  name: qjhwot4hl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qjhwot4hl-nodejs 
